### ISSUE TITLE
Recaptcha upgrade

### ISSUE THREAD

**Issue by superst** [renlok/WeBid#117]
I see the old captcha has been removed. Now when i go into register page etc, i get blank page, until i change the setting in admin from 'image' to either 'none' or 'recaptcha'

So either the image option needs removing or the old captcha needs reinstating, for that selection to work, so we still have 3 options...or another fix :D

**Comment by Nozlaf** [comment]
yes sorry I've accidentally included part of another branch in this update, the intent here was to move the simple php based captcha used for the image type to the /includes folder but ive only removed it from the /inc folder

fix posting soon

**Comment by renlok** [comment]
is this fixed?

**Comment by superst** [comment]
I think this was the commit that fixed it https://github.com/renlok/WeBid/commit/426506859059aa12808c84ba14bd8732603e484b
