### ISSUE TITLE
unable to buy anything

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#144]
So i'm running the current source at the moment and I cant buy anything
bidding works, auction ends or is closed (after applying my fix for listing your own auctions)
 and the buyer is notified that the auction has ended and they have won the auction but the table listing the winners is never populated

**Comment by renlok** [comment]
I made some database changes, might that be causing the problem as it was working fine on my test machine

**Comment by Nozlaf** [comment]
ah yeah I realise this but the changes I don't think are being applied by the installer, there were also some other commits which broke some functionality which I've fixed on my most recent pull request
