### ISSUE TITLE
Merge user + admin accounts

### ISSUE THREAD

**Issue by renlok** [renlok/WeBid#172]
Why where they ever seperate

**Comment by aucsta** [comment]
What's happening about this

**Comment by aucsta** [comment]
any ideas on how to do this

**Comment by BabyDunk** [comment]
a moderators account would be a nice add also with limited view of admin panel

**Comment by renlok** [comment]
Moved to [To Do wiki](https://github.com/renlok/WeBid/wiki/To-DO) page
