### ISSUE TITLE
Images doesnt save after upload

### ISSUE THREAD

**Issue by webbiz2** [renlok/WeBid#206]
Is there someone that can PLEASE help me?! I have been trying to fix this issue for 2  days. Every time I upload an image in photo gallery, it simply doesn't save & also doesn't display in the auction images. I joined www.webidsupport.com but I am unable to even ask a question on the site.

**Comment by MESWEB** [comment]
Give us more detail about Your host and check a CHMOD of uploading folder.

**Comment by webbiz2** [comment]
PHP version: 5.5.36 on Linux. Permissions are set to 7555

**Comment by MESWEB** [comment]
Ok. Go to [http://errors.win](errors.win) and post new topic there on PHP board and I will help You.

**Comment by webbiz2** [comment]
still not working
