### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by MESWEB** [renlok/WeBid#210]
Function of search.php and adsearch.php not working for finding any auction by id auction. If i type 1 and search the results show me two auctions = 1 and 4 id. Search function should be separated for ID and description auction because if You search string "1" then result displays auction ID1 and every auctions with 1 in description or title. Good solution should be to make if statement for string "#{AUCTION_ID}" if somebody wants find auction by ID he should search by  add # to number of ID.

**Comment by MrMerkucio** [comment]
Hello. Find on main page not working. I write name my auction and push button "Search for it", "No items found" :-(... adsearch.php working nice, find my auction. Theme modern, version 1.2.

**Comment by MESWEB** [comment]
Hi. For me too not working search.php. Please somebody fix this important function.

**Comment by MrMerkucio** [comment]
Ok.. Thank you. I download with *timw255/WeBid, *your register.php file 
has errors in line country.

Registration new user impossible. Page not loaded. Log errors >>

Unknown error type: [8] Array to string conversion on 
web.net\register.php line 431
Unknown error type: [2] Illegal string offset 'country' on 
web.net\register.php line 432
Unknown error type: [2] Illegal string offset 'country' on 
web.net\register.php line 436
Unknown error type: [2] Illegal string offset 'country' on 
web.net\register.php line 440


_Your code note work_


  foreach($countries as $country)
{
     $country .= '<option value="' . $country['country'] . '"';
     if ($country['country'] == $selcountry)
     {
         $country .= ' selected';
     }
     elseif ($system->SETTINGS['defaultcountry'] == $country['country'])
     {
         $country .= ' selected';
     }
     $country .= '>' . $country['country'] . '</option>' . "\n";
}



25.06.2016 23:48, MESWEB пишет:
> Hi. For me too not working search.php. Please somebody fix this 
> important function.

**Comment by hydroid7** [comment]
Can someone please tell me what commit solves this problem?

**Comment by MrMerkucio** [comment]
Hi. No :-(


22.09.2016 13:05, hydroid7 пишет:

**Comment by hydroid7** [comment]
😂😂👌
Ok thx

**Comment by tank-crd** [comment]
I am currently using version 1.2.1 and the search function does not work at all. I have e tried entering many different search terms with no luck.

**Comment by blumenow** [comment]
I'm having the same problem, it works from the Advanced search, just not the normal one from the header.
