### ISSUE TITLE
Error with PDO

### ISSUE THREAD

**Issue by MESWEB** [renlok/WeBid#218]
**PHP 7.0.8**
Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\aukcje\includes\database\DatabasePDO.php on line 82

**Comment by renlok** [comment]
What page where you trying to load?

**Comment by MESWEB** [comment]
Hmm I don't know exactly what page make this error but I remember I use v1.2.0 on localhost. I think I try open index.php
