### ISSUE TITLE
Uploaded images sometimes have UPPER CASE file extension, does not match WeBid URL

### ISSUE THREAD

**Issue by Telecomgeek** [renlok/WeBid#261]
I found the problem in PluploadHandler.php, Github needs updated with the fix.

Here is the problem:
line 168 and line 169

$final_file_path = strtolower($file_path);
rename($tmp_path, $file_path);

Should be:

$final_file_path = strtolower($file_path);
rename($tmp_path, $final_file_path);

**Comment by renlok** [comment]
would you also need to replace
'name' => $file_name,
with
'name' => strtolower($file_name),

**Comment by renlok** [comment]
Is this resolved now?

**Comment by Telecomgeek** [comment]
Yes
