### ISSUE TITLE
functions_ajax.php checks array for $fileName but writes $final_file_name

### ISSUE THREAD

**Issue by Telecomgeek** [renlok/WeBid#262]
I have found a related problem in **functions_ajax.php**;

My scenario is uploading a 14MB picture to an auction with the name "testimage.JPG". As the image is uploaded and "chunked" out in 1MB chunks, **functions_ajax.php** was adding each chunk to the $_SESSION['UPLOADED_PICTURES']. So after uploading this image, my auction would show 14 instances of this picture because the filename was written to $_SESSION['UPLOADED_PICTURES'] as each "chunk" was written out. Here is the problem code in **functions_ajax.php**:

// resize picture
            $uploader->resizeThumbnailImage($targetDir . '/' . $fileName, $system->SETTINGS['gallery_max_width_height']);
            if (!in_array($fileName, $_SESSION['UPLOADED_PICTURES']))
            {
                $final_file_name = strtolower($fileName);
                array_push($_SESSION['UPLOADED_PICTURES'], $final_file_name);
                if (count($_SESSION['UPLOADED_PICTURES']) == 1)
                {
                    $_SESSION['SELL_pict_url_temp'] = $_SESSION['SELL_pict_url'] = $final_file_name;
                }
            }

The problem is the code looks for **_$fileName_** in the array but then writes **_$final_file_name_** to the array if **_$fileName_** is not found. Obviously if **_$fileName_** does not equal **_$final_file_name_** this is a problem, and in fact in my case the **_$fileName_** ends with JPG and **_$final_file_name_** ends with jpg. So after each chunk, **_$final_file_name_** is added to the array. Here is the updated fixed code:

// resize picture
            $uploader->resizeThumbnailImage($targetDir . '/' . $fileName, $system->SETTINGS['gallery_max_width_height']);
            $final_file_name = strtolower($fileName);
            if (!in_array($final_file_name, $_SESSION['UPLOADED_PICTURES']))
            {
                array_push($_SESSION['UPLOADED_PICTURES'], $final_file_name);
                if (count($_SESSION['UPLOADED_PICTURES']) == 1)
                {
                    $_SESSION['SELL_pict_url_temp'] = $_SESSION['SELL_pict_url'] = $final_file_name;
                }
            }

**Comment by renlok** [comment]
Is this resolved now?

**Comment by Telecomgeek** [comment]
Yes
