### ISSUE TITLE
duplicate code could be optimized

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#267]
quite a lot of code is duplicated throughout webid
I think it would be good to remove this duplicated code in the interest of making things easier to improve on and develop moving forward
i understand its a big job, ive been on holidays for 2 weeks considering tackling it now but would be interested if others see this as an issue

**Comment by renlok** [comment]
Yeah I definalty want to get this done as part of the general code cleanup for webid

**Comment by aucsta** [comment]
This can now be closed

**Comment by aucsta** [comment]
is this finished or is there still more work to be done
