### ISSUE TITLE
support for mysql 5.5 ?

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#273]
I've noticed that you are using 

> default  CURRENT_TIMESTAMP

but mysql 5.5 doesnt support it I believe this is only on 5.6 and above

mysql 5.5 supports timestamp datatypes with the default of CURRENT_TIMESTAMP  but not datetime data types with a default of CURRENT_TIMESTAMP

so effectively at the moment this is broken on mysql 5.5 which could be a big issue as 5.5 is pretty much standard

**Comment by Nozlaf** [comment]
if that is to be the way things are I would suggest making the installer check for mysql 5.6+ or mariadb 10+

**Comment by renlok** [comment]
What would be the best way to deal with this remove the default value and alter each INSERT query to add the date manaully?

**Comment by Nozlaf** [comment]
I think you could just use the timestamp data type, Ill do some testing

**Comment by Nozlaf** [comment]
as a test I tried to create the admin users in a mysql5.5 compatible way
it only allows ONE timestamp field so I had to ditch t he detault value on the lastlogin
but it works


```
CREATE TABLE webid_adminusers (
  `id` int(11) NOT NULL auto_increment,
  `username` varchar(32) NOT NULL,
  `password` varchar(60) NOT NULL,
  `password_type` INT(1) NOT NULL DEFAULT '1',
  `hash` varchar(5) NOT NULL default '',
  `created` timestamp default CURRENT_TIMESTAMP,
  `lastlogin` datetime,
  `status` tinyint(1) NOT NULL default '0',
  `notes` text,
  PRIMARY KEY  (`id`)
) ;
```

**Comment by renlok** [comment]
This is fine it makes sense to have any created fields as a timestamp

**Comment by Nozlaf** [comment]
not sure if these issues existed before this update or not but some debugging is required


tried to access user control panel and sell an item

```
[Tue Sep 27 21:18:53.408813 2016] [:error] [pid 3564] [client 192.168.1.3:60516] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2053 ' in /var/www/html/WeBid-mysql5.5_fix/includes/database/DatabasePDO.php:141\nStack trace:\n#0 /var/www/html/WeBid-mysql5.5_fix/includes/database/DatabasePDO.php(141): PDOStatement->fetch(2)\n#1 /var/www/html/WeBid-mysql5.5_fix/user_menu.php(98): DatabasePDO->result('total')\n#2 /var/www/html/WeBid-mysql5.5_fix/user_menu.php(140): get_reminders('1')\n#3 {main}\n  thrown in /var/www/html/WeBid-mysql5.5_fix/includes/database/DatabasePDO.php on line 141
[Tue Sep 27 21:19:32.979733 2016] [:error] [pid 3561] [client 192.168.1.3:60528] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (P1.00D)' in /var/www/html/WeBid-mysql5.5_fix/sell.php:113\nStack trace:\n#0 /var/www/html/WeBid-mysql5.5_fix/sell.php(113): DateInterval->__construct('P1.00D')\n#1 {main}\n  thrown in /var/www/html/WeBid-mysql5.5_fix/sell.php on line 113, referer: http://192.168.1.201/WeBid-mysql5.5_fix/sell.php

```

**Comment by renlok** [comment]
I think this issue is now fixed
