### ISSUE TITLE
all user accounts getting suspended after selling/buying the first item automatically , even for zero balance

### ISSUE THREAD

**Issue by platzo** [renlok/WeBid#417]
all user accounts getting suspended after selling/buying the first item automatically , even for zero balance on live payments . Tested on Auction listing only 
<img width="1180" alt="screen shot 2017-01-25 at 6 20 58 pm" src="https://cloud.githubusercontent.com/assets/25323152/22295505/9b7002d2-e330-11e6-8f8e-d98acd55ddba.png">
<img width="1187" alt="screen shot 2017-01-25 at 6 21 28 pm" src="https://cloud.githubusercontent.com/assets/25323152/22295516/a224db2a-e330-11e6-8990-fa847379ee01.png">
<img width="1204" alt="screen shot 2017-01-25 at 6 22 30 pm" src="https://cloud.githubusercontent.com/assets/25323152/22295525/a5ff62f6-e330-11e6-9c39-f0659e438bca.png">

**Comment by renlok** [comment]
This is how live payments work

**Comment by platzo** [comment]
how a buyer account suspended for 0.00 balance and there is no way for buyer to retrieve their account ?
