### ISSUE TITLE
Cant create auction

### ISSUE THREAD

**Issue by Kawobei** [renlok/WeBid#420]
[Wed Mar 08 12:26:14.377234 2017] [:error] [pid 11509] [client 10.1.10.13:16740] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (P1.00D)' in /var/www/webid/sell.php:99\nStack trace:\n#0 /var/www/webid/sell.php(99): DateInterval->__construct('P1.00D')\n#1 {main}\n  thrown in /var/www/webid/sell.php on line 99, referer: https://sunibid.sunitafe.edu.au/sell.php

Trying to sell item.
End Date is 1 day, custom start date is turned off.
Dateformat is DD/MM/YYYY
We are version 1.2.2

**Comment by Naf576** [comment]
fixed the problem by changing the start and end datatype in auctions table to Date

**Comment by renlok** [comment]
Is this still a problem as I cannot reproduce it in current

**Comment by Kawobei** [comment]
I think the issue was we had to leave newsletter on or something like that and then lots of things started working. Close the issue.
