### ISSUE TITLE
Register not working

### ISSUE THREAD

**Issue by MESWEB** [renlok/WeBid#423]
Package called reCaptcha not working properly.  After enter my keys of recaptcha to settings of WebId I can't register any users.  Recaptcha was work only few times at the beginning and next stop work. I check reason and I found this code makes this issue
```php
 if ($system->SETTINGS['spam_register'] == 2 && !$resp) {
            $ERR = $MSG['752'];
```

**Comment by ksperr** [comment]
what is the error you receive?

**Comment by MESWEB** [comment]
No error. Just seems to look like some issue from recaptcha package.
