### ISSUE TITLE
Cant use DateInterval due to float

### ISSUE THREAD

**Issue by BabyDunk** [renlok/WeBid#424]
On line 99 of sell.php, we have a problem . DataInterval only allow integers but for the auction duration we use floats to get parts of a day. 

This does work, a simple fix is to change this
` $start_datetime->add(new DateInterval('P' .  $duration . 'D'));`

To this 
` $start_datetime->add(new DateInterval('P' . intval($duration) . 'D'));`

**Comment by webhp** [comment]
You would want to make a pull request to suggest these changes.

**Comment by renlok** [comment]
Added the changes thanks
