### ISSUE TITLE
payment method not saving when registering

### ISSUE THREAD

**Issue by aucsta** [renlok/WeBid#429]
when I fill in the registration form and enter my PayPal details, it doesn't save them so I have to enter them again under my account. Also when I select this payment type as required, on my register page it says PayPal addresschecked, how do I get rid of the checked bit

**Comment by MESWEB** [comment]
Can we switch off this form in admin panel?

**Comment by aucsta** [comment]
Yeh but I want it on my registration page so users only have to do it once

**Comment by aucsta** [comment]
Yeh but I want it on my registration page so users only have to do it once
