### ISSUE TITLE
Non-working site

### ISSUE THREAD

**Issue by mov4un** [renlok/WeBid#436]
Will your forum work? He is very useful.
Perhaps you need some help?

**Comment by MESWEB** [comment]
Seems like project has been switch off.

**Comment by BabyDunk** [comment]
I don't think the project is switch off, after all Renlok done an update only 13 days.  i don't know if Renlok has the time to sort the forum out, as there was a lot of spam bombarding it everyday. and a lot of users were getting annoyed including myself. so i presume the forum has been taken down until such times as the problem can be sorted. 

this is all speculation on my part, as i have not spoken with anyone concerning this matter.  although i check every day hoping that the forum is back online. Hopefully not be much longer

**Comment by renlok** [comment]
Hey all sorry projects not dead but the site was hacked and taken offline. I have busy but when I have a few hours spare I will try to get it back online again hopefully by the end of the week.

**Comment by mov4un** [comment]
Thank you. Very much looking forward to the resumption of the forum

**Comment by BabyDunk** [comment]
Look forward to it 💃

**Comment by MESWEB** [comment]
I was told You this project is going down. I can help with coding. I have made FB login to webid script. Check here:

**Comment by mov4un** [comment]
Maybe you still need help rebuilding the site?

**Comment by MESWEB** [comment]
What You mean rebuilding site?

**Comment by mov4un** [comment]
We can provide hosting

**Comment by 2bruce2** [comment]
So, how's the project going. I am new here, finding the webid fits my own project wonderfully. hope the forum can come back online ASAP. Lots to discuss and communicate. Renlok seems really busy those days.

**Comment by superst** [comment]
Am sure it will be back up at some point. Patiently waiting :)

**Comment by renlok** [comment]
It's back online, thanks for being so patient.
