### ISSUE TITLE
register.php? page not working

### ISSUE THREAD

**Issue by salfonseca1** [renlok/WeBid#437]
When you click on the "Register now"= register.php? I get a "blank" page.... any ideas?

**Comment by MESWEB** [comment]
Url site?

**Comment by salfonseca1** [comment]
washingtonunified.org/Auction

**Comment by MESWEB** [comment]
Chcek Your server errors and php errors

**Comment by salfonseca1** [comment]
negative... no server errors

**Comment by salfonseca1** [comment]
Something odd that I noticed is that when I view the source code using chrome the page is empty…..  see screenshot
<img width="1280" alt="screen shot 2017-06-19 at 11 03 03 pm" src="https://user-images.githubusercontent.com/27232483/27319055-6db73050-5544-11e7-84c2-61a76865406c.png">

**Comment by MESWEB** [comment]
Yes I know that. I was see this yesterday. That's why You should check php errors and logs from the server. Try display errors.

**Comment by salfonseca1** [comment]
![webid_administration_back-end](https://user-images.githubusercontent.com/27232483/27319725-b640b848-5547-11e7-92d9-9985b2bcc8ca.jpg)

**Comment by salfonseca1** [comment]
Are any of those errors a cause for my register page not to load?

**Comment by salfonseca1** [comment]
Problem resolved! I upgraded the php sql server to 5.6.
