### ISSUE TITLE
Not working IF PAGE

### ISSUE THREAD

**Issue by MESWEB** [renlok/WeBid#438]
I'm trying using if statement for html tags in global header and global footer template files. Here is my example:
```html
<!-- IF PAGE eq register -->
```
But without success. Any way other code is working perfect:
```html
<!-- IF PAGE eq sell -->
```
How to fix this for Page Register and others?

**Comment by renlok** [comment]
you are missing quotation marks
it needs to be

**Comment by MESWEB** [comment]
Why You close this issue? Your solution didn't fix nothing. I was trying this before I post here.
