### ISSUE TITLE
Issue with loading images in home page

### ISSUE THREAD

**Issue by MESWEB** [renlok/WeBid#442]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

I get this error. Opera last version.

**Comment by BabyDunk** [comment]
did you check your server error logs?? that's were you usually find the logs for a 500 error

**Comment by MESWEB** [comment]
couldn't create child process: /xxx/sbin/xxx for /xxx/xxxx/public_html/xp.pl/getthumb.php, referer: https://xp.pl/
