### ISSUE TITLE
spam prevention

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#465]
the current concept of pre-populating the database with blocked domains is a battle that can never be won, would be better to implement something like this
http://www.v-nessa.net/2010/07/16/simple-php-script-for-rbl-checking

**Comment by MESWEB** [comment]
This is very old solution and not supported. Better find actual list of blacklist of emails website.

**Comment by Nozlaf** [comment]
I dont think you understand what the script does

it uses the Net_DNSBL pear module which checks if a given Host or URL is listed on an DNS-based Blackhole List (DNSBL, Real-time Blackhole List or RBL) or Spam URI Realtime Blocklist (SURBL)

utilising this method would mean that the list is always up to date all we would need to present to the admin would be the option to turn it on or off and the list of IP's that the queries would be sent to

**Comment by renlok** [comment]
Links dead
