### ISSUE TITLE
Not able to create admin login

### ISSUE THREAD

**Issue by ugintl** [renlok/WeBid#466]
I downloaded the latest version and everything went well, but I am not able to create admin username and password. I did follow the solution by emptying up the adminusers table in the database, but nothing happens. I still see blank page. After lot of trying, the username and password was created, but then it was not logging in. Again blank page. Then I installed it using softaculous installer and it installed and I was able to login as admin as the username and password was created during installation. The problem is that it has the old version 1.2.1 and I guess this is not a solution to the problem. You must do something about it. Why not include username and password creation during install.

What should I do now?

**Comment by aucsta** [comment]
try uploading it again with FileZilla that what I am using and I am not having any problems

**Comment by ugintl** [comment]
Thank you for your reply. I do not understand one thing. What does uploading has to do with it? I used cpanel file manager to upload the files. I downloaded the master version.

**Comment by ugintl** [comment]
One more thing. When I try to download from Webid website, it downloads 1.2.1 version and not the latest one. That is why I came to github for latest version.

**Comment by aucsta** [comment]
I have no idea I'm just saying it must be to do with your end because I don't have this problem and I'm using the latest version
