### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aucsta** [renlok/WeBid#467]
Unknown error type: [4096] Object of class DateTime could not be converted to string on /hermes/bosnaweb07a/b1189/ipg.aucstacom/includes/database/DatabasePDO.php line 79

**Comment by renlok** [comment]
Where do you get this error what where you doing?

**Comment by aucsta** [comment]
I get it in admin error log even on a fresh install. When I reset the log and carry on using the main site it comes back after a few minutes

**Comment by MESWEB** [comment]
I was notice this same error but I was fix that by editing time function.

**Comment by aucsta** [comment]
How do I do that

**Comment by MESWEB** [comment]
Which file You try open when this error is showing?

**Comment by aucsta** [comment]
Just by accessing the home page

**Comment by aucsta** [comment]
But it never multiplies as it would if there was a constant error

**Comment by MESWEB** [comment]
I don't remember exactly where is this bug because I was fix that long time ago. What I remember is that in databse is somewhere bad format of time (old unix time in current timestamp) so maybe this is issue.

**Comment by aucsta** [comment]
I just thought you should be aware of it

**Comment by MESWEB** [comment]
```php
 foreach ($params as $val) {
                $this->lastquery->bindParam($val[0], $val[1], $val[2]);
            }```
This code coming from function **query** that means script asking database with faulty value or script receive faulty data time from database. Sorry I'm upgrading manually this script and analyse it. So that's why I don't pay attention for errors.
