### ISSUE TITLE
Advisory from Netsparker - Webid 1.2.2 - Reflected and Blind XSSes

### ISSUE THREAD

**Issue by DanielBishtawi** [renlok/WeBid#522]
Hello,

While testing the Netsparker web application security scanner we identified Reflected XSS and Blind XSS vulnerabilities in Webid. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by MESWEB** [comment]
@DanielBishtawi Can U show us more info here?

**Comment by DanielBishtawi** [comment]
@renlok Would you like us to disclose the technical details here? Or disclose the technical details via email?

**Comment by renlok** [comment]
I'll send you an email
