### ISSUE TITLE
Auctions help mollie integration payment gateway

### ISSUE THREAD

**Issue by denetwerkspecialist** [renlok/WeBid#527]

**Comment by MESWEB** [comment]
@denetwerkspecialist  - first fix PayPal payment - this function:

> public function paypal_validate()

Is outdated and need to be replace with new getaway. I have already done this by updating PayPal implementation.

**Comment by denetwerkspecialist** [comment]
We have paypal worked now, but not mollie

**Comment by denetwerkspecialist** [comment]
After click buy now (Ideal) it goes to the checkout from Mollie, but the amount is wrong! How can we get the right amount with a query (See pitures). Now the query is:

$query = "SELECT w.id, w.winner, w.auc_title, w.auc_shipping_cost, a.shipping_cost, w.bid, w.qty, w.auction As auc_id, a.additional_shipping_cost, a.shipping FROM " . $DBPrefix . "winners w
		JOIN " . $DBPrefix . "auctions a ON (a.id = w.auction)
		WHERE w.paid = 0 AND w.winner = :user_id ORDER BY a.id";

![1](https://user-images.githubusercontent.com/55900523/70159826-d1a16e80-16b9-11ea-9beb-01d9e8f42049.PNG)
![2](https://user-images.githubusercontent.com/55900523/70159827-d23a0500-16b9-11ea-9760-ce07b7bc34b7.PNG)

**Comment by MESWEB** [comment]
Do you want to tell me paypal function in this file working fine?
https://github.com/denetwerkspecialist/Auctions/blob/master/includes/class_fees.php
Stop kidding me.

OK let's talk about mollie. It's easy to implement new payment getaway. How this mollie work? Same like paypal? Using e-mail address for sending and receiving money?

**Comment by denetwerkspecialist** [comment]
How ? Send us that infoMollie is payment gateway for multi Banks and credit card paymentsVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: MESWEB <notifications@github.com> Datum: 04-12-19  17:02  (GMT+01:00) Aan: renlok/WeBid <WeBid@noreply.github.com> Cc: denetwerkspecialist <info@denetwerkspecialist.com>, Mention i<mention@noreply.github.com>i Onderwerp: Re: [renlok/WeBid] Auctions help mollie integration payment gateway (#527) @denetwerkspecialist  - first fix PayPal payment - this function:

public function paypal_validate()

Is outdated and need to be replace with new getaway. I have already done this by updating PayPal implementation.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/renlok/WeBid/issues/527?email_source=notifications\u0026email_token=ANKPS2ZTY3BH5JTWMAZCWDLQW7IBZA5CNFSM4JVKSFX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF5QOWA#issuecomment-561710936",
"url": "https://github.com/renlok/WeBid/issues/527?email_source=notifications\u0026email_token=ANKPS2ZTY3BH5JTWMAZCWDLQW7IBZA5CNFSM4JVKSFX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF5QOWA#issuecomment-561710936",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Nozlaf** [comment]
so you took the code, from this project which had licence notices embedded in the files and removed the licence information and then "copyrighted" our code as your own and now you are here asking us to fix your code?


you need to step back and look at yourself.

**Comment by denetwerkspecialist** [comment]
It is simple Webid = DEAD - Had many Errors/Bugs
It is still Open Source , but we want so "see"how many people are using it so that why we added the license system, the github version is free, everybody can get as many license as they want.
We fixed many bugs
We rewrote many parts of the code and added many new things improved the install script
Yes we do got a Paid version where we added new stuff with our from us
So what is the problem here?

**Comment by Nozlaf** [comment]
put our copyright notices back, are you crazy? 
imagine i came to your house, stole your car, then came back and asked you to replace the oil filter

**Comment by Nozlaf** [comment]
interesting that you would rather delete your repo than attribute the original code to the writers, good luck fitting in with open source in the future

**Comment by denetwerkspecialist** [comment]
We need some time to change the headers of the files so that's why we deleted the files for now.
Regarding @Nozlaf  "our copyright notices" We will put back the old Open Source Free Software text but with our Name due to the fact we fixed many bugs and added many new stuff.

@Nozlaf "our copyright notices" Are you RenLock?

**Comment by MESWEB** [comment]
@denetwerkspecialist: @Nozlaf is contributor of this project and he has improve this project.

**Comment by Nozlaf** [comment]
@denetwerkspecialist  the copyright notices said copyright WeBid not  copyright renlok, don't fight it, i've just asked you to do what is right, restore our project copyright notices, attribute the code to this project, do what you want with it once you have attributed it this project its open source, enjoy it 
you admitted to removing the copyright notices, yet don't seem to think it's an issue?
