### ISSUE TITLE
Does not work when migrating to live server

### ISSUE THREAD

**Issue by diakosibatman** [renlok/WeBid#85]
When I am finished installing fresh WeBid installation in live server, the create admin just loops again and again when clicking insert button. There's nothing happen.

**Comment by Nozlaf** [comment]
I encountered the same thing after using a fresh install with an old database

can you confirm you are not using an older database?

**Comment by diakosibatman** [comment]
Yes. I use new database. And until now, it still not working. I think there's a server compatibility issue with WeBid. I need help. It's frustrating.

**Comment by Nozlaf** [comment]
I think this issue has been resolved and can be closed
