### ISSUE TITLE
timezones = :(

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#86]
I've made  a fix for the registration page to include the default timezone but it made me realise how timezones are being handled by WeBid

I think this needs to be completely re-written

WeBid currently cannot support timezones which are + or - .5  of a hour, for example GMT + 9.5 (South Australia and Northern Territory Australia)

currently no support of daylight savings time which means GMT+10 is broken for eastern states in Australia where three states and one territory have DST and one state does not have DST

currently no ability  to change timezone definition from the admin interface

As I am using WeBid for something at work and I don't really need this functionality I am reluctant to say I will do the work but hopefully someone else will do it, if not I will come back to it in a few months when I am not so busy

**Comment by renlok** [comment]
Moved to mantis
