### ISSUE TITLE
Pay Now button not working

### ISSUE THREAD

**Issue by diakosibatman** [renlok/WeBid#90]
I used updated WeBid github files. 
I already put paypal address of buyer, seller and admin.

When the buyer clicks the Pay Now button, it does not go to other page, instead, will just proceed to itself as if nothing happens when clicking.
![error](https://cloud.githubusercontent.com/assets/4057137/9582493/3be3e176-5038-11e5-9698-4632923a3722.png)

Please help.

**Comment by Nozlaf** [comment]
Yeah I can confirm this is the case on my dev environment I'll be investigatting the cause today

**Comment by Nozlaf** [comment]
was a bug in the theme but was fixed about 5 days ago, update to the latest version and the bug should be resolved
I was still experiencing the bug because I run a custom theme based on default
