### ISSUE TITLE
installer not working

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#91]
installer fails with a "access denied" which is being generated by class_db_handle.php

**Comment by superst** [comment]
Same issue here

**Comment by renlok** [comment]
I think this is fixed in the recent commit
https://github.com/renlok/WeBid/commit/c92c4c4df84969c17af8c0ab46f3ad3bf792210b

**Comment by Nozlaf** [comment]
still doesnt work because the db handler class is testing that inwebid is set which it isnt because we dont call common.php
but after adjusting that it installs
then it dies because there are other errors.

**Comment by lod121** [comment]
Can confirm that the latest commit fixes the installer. It still dies because of other errors though, which appear to be fixed in Nozlaf's fork.

**Comment by Nozlaf** [comment]
Issue has now been resolved
