### ISSUE TITLE
bug with fees?

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#94]
spent the whole day fixing issues but have encountered one that I am not inclined to touch as I am not using fees on my site

when accessing the Sell pages these errors are logged

03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: bolditem_fee on /var/www/html/WeBid/includes/functions_sell.php line 449 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: bolditem_fee on /var/www/html/WeBid/includes/functions_sell.php line 451 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: hlitem_fee on /var/www/html/WeBid/includes/functions_sell.php line 454 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: hlitem_fee on /var/www/html/WeBid/includes/functions_sell.php line 456 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: subtitle_fee on /var/www/html/WeBid/includes/functions_sell.php line 459 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: subtitle_fee on /var/www/html/WeBid/includes/functions_sell.php line 461 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: picture_fee on /var/www/html/WeBid/includes/functions_sell.php line 479 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: picture_fee on /var/www/html/WeBid/includes/functions_sell.php line 481 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: excat_fee on /var/www/html/WeBid/includes/functions_sell.php line 484 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: excat_fee on /var/www/html/WeBid/includes/functions_sell.php line 486 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: bolditem_fee on /var/www/html/WeBid/includes/functions_sell.php line 449 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: bolditem_fee on /var/www/html/WeBid/includes/functions_sell.php line 451 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: hlitem_fee on /var/www/html/WeBid/includes/functions_sell.php line 454 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: hlitem_fee on /var/www/html/WeBid/includes/functions_sell.php line 456 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: subtitle_fee on /var/www/html/WeBid/includes/functions_sell.php line 459 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: subtitle_fee on /var/www/html/WeBid/includes/functions_sell.php line 461 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: picture_fee on /var/www/html/WeBid/includes/functions_sell.php line 479 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: picture_fee on /var/www/html/WeBid/includes/functions_sell.php line 481 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: excat_fee on /var/www/html/WeBid/includes/functions_sell.php line 484 
03-09-2015, 16:42:13: Unknown error type: [8] Undefined index: excat_fee on /var/www/html/WeBid/includes/functions_sell.php line 486

**Comment by renlok** [comment]
Think this is fixed
https://github.com/renlok/WeBid/commit/8041b636eeb1fae92f71c635842fb90833d75de8
