### ISSUE TITLE
issue with "selling" from My control panel

### ISSUE THREAD

**Issue by Nozlaf** [renlok/WeBid#95]
when accessing the "selling" tab on my control panel and then selecting "active auctions" often the page will load but be empty
clicking between tabs will eventually make it load
not sure as to the reason but I will investigate this in the next few days if no-one else does

luckily it does produce some log data

03-09-2015, 16:42:00: Unknown error type: [8] Undefined index: ca_ord on /var/www/html/WeBid/yourauctions.php line 141 
03-09-2015, 16:42:00: Unknown error type: [8] Undefined index: ca_type on /var/www/html/WeBid/yourauctions.php line 141 
03-09-2015, 16:42:05: Unknown error type: [8] Undefined index: ca_ord on /var/www/html/WeBid/yourauctions.php line 141 
03-09-2015, 16:42:05: Unknown error type: [8] Undefined index: ca_type on /var/www/html/WeBid/yourauctions.php line 141

**Comment by renlok** [comment]
I cannot reproduce this, can anyone else or can I assume its been fixed?
